[build]
# Use incremental compilation for development builds
incremental = true

[target.x86_64-apple-darwin]
# Cache compiled dependencies to speed up builds
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[profile.dev]
# Optimize dev builds for faster compile time
opt-level = 0
debug = true
incremental = true

[profile.test]
# Optimize test builds
opt-level = 0
debug = true
incremental = true